image: python:latest

services:
  - postgres:latest
stages:
- test
- analysis

variables:
  POSTGRES_DB: ci

cache:
  paths:
  - ~/.cache/pip/

test:
  stage: test
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - python -V
  - pip install -r requirements.txt
  - pip install coverage
  - coverage run --source='.' manage.py test gitlab_ci_example_django
  - python manage.py test --settings gitlab_ci_example_django.settings.ci
