image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: ci

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - pip install -r requirements.txt
  -

test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - python manage.py test --settings gitlab_ci_example_django.settings.ci

stages:
- analysis

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://79.143.180.32:9000
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner -Dsonar.projectKey=gitlab-ci-example-django -Dsonar.sources=. -Dsonar.host.url=http://79.143.180.32:9000 -Dsonar.login=3567c1e6807fbba7cde681360e14a62261fda144