image: python:latest

services:
  - postgres:latest
stages:
- test
- analysis

variables:
  POSTGRES_DB: ci

cache:
  paths:
  - ~/.cache/pip/

test:
  stage: test
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - python -V
  - pip install -r requirements.txt
  - pip install coverage
  - coverage run --source='.' manage.py test gitlab_ci_example_django
  - coverage report -m
  - python manage.py test --settings gitlab_ci_example_django.settings.ci

sonarqube-reports:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_ANALYSIS_MODE: publish
  script:
  - gitlab-sonar-scanner -Dsonar.projectKey=gitlab-ci-example-django -Dsonar.sources=. -Dsonar.host.url=http://sonarqube-server -Dsonar.login=xxxxxxxxxxxxxxxxxxxxxxxxx